import { createSlice } from "@reduxjs/toolkit";
const data = [
  [
    {
      id: 1,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ali",
      lastname: "sayed",
      fullname: "ali sayed",
      email: "ali@gmail.com",
      age: 18,
      phone: "01143219323",
      access: "admin",
    },
    {
      id: 2,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "sara",
      lastname: "alaa",
      fullname: "sara ala",
      email: "sara@gmail.com",
      age: 22,
      phone: "0123124454",
      access: "admin",
    },
    {
      id: 3,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "hager",
      lastname: "ali",
      fullname: "hager ali",
      email: "hager@gmail.com",
      age: 33,
      phone: "0102423423",
      access: "user",
    },
    {
      id: 4,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "khaled",
      lastname: "ahmed",
      fullname: "khaled ahmed",
      email: "khaled@gmail.com",
      age: 20,
      phone: "01184319323",
      access: "user",
    },
    {
      id: 5,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ahmed",
      lastname: "ali",
      fullname: "ahmed ali",
      email: "ahmed@gmail.com",
      age: 32,
      phone: "01243219323",
      access: "admin",
    },
    {
      id: 6,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ali",
      lastname: "sayed",
      fullname: "ali sayed",
      email: "ali@gmail.com",
      age: 25,
      phone: "0102219323",
      access: "admin",
    },
    {
      id: 7,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "mohamed",
      lastname: "ali",
      fullname: "mohamed ali",
      email: "mohamed@gmail.com",
      age: 18,
      phone: "01053219323",
      access: "admin",
    },
    {
      id: 8,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "sara",
      lastname: "sayed",
      fullname: "sara sayed",
      email: "sara@gmail.com",
      age: 26,
      phone: "013214723",
      access: "user",
    },
  ],
  [
    {
      id: 9,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "sara",
      lastname: "sayed",
      fullname: "sara sayed",
      email: "sara@gmail.com",
      age: 26,
      phone: "013214723",
      access: "user",
    },
    {
      id: 10,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "sara",
      lastname: "alaa",
      fullname: "sara ala",
      email: "sara@gmail.com",
      age: 22,
      phone: "0123124454",
      access: "admin",
    },
    {
      id: 11,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ali",
      lastname: "sayed",
      fullname: "ali sayed",
      email: "ali@gmail.com",
      age: 18,
      phone: "01143219323",
      access: "admin",
    },
    {
      id: 12,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "hager",
      lastname: "ali",
      fullname: "hager ali",
      email: "hager@gmail.com",
      age: 33,
      phone: "0102423423",
      access: "user",
    },
    {
      id: 13,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ahmed",
      lastname: "ali",
      fullname: "ahmed ali",
      email: "ahmed@gmail.com",
      age: 32,
      phone: "01243219323",
      access: "admin",
    },
    {
      id: 14,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "khaled",
      lastname: "ahmed",
      fullname: "khaled ahmed",
      email: "khaled@gmail.com",
      age: 20,
      phone: "01184319323",
      access: "user",
    },
    {
      id: 15,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "mohamed",
      lastname: "ali",
      fullname: "mohamed ali",
      email: "mohamed@gmail.com",
      age: 18,
      phone: "01053219323",
      access: "admin",
    },
    {
      id: 16,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ali",
      lastname: "sayed",
      fullname: "ali sayed",
      email: "ali@gmail.com",
      age: 25,
      phone: "0102219323",
      access: "admin",
    },
  ],
  [
    {
      id: 17,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "sara",
      lastname: "alaa",
      fullname: "sara ala",
      email: "sara@gmail.com",
      age: 22,
      phone: "0123124454",
      access: "admin",
    },
    {
      id: 18,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "hager",
      lastname: "ali",
      fullname: "hager ali",
      email: "hager@gmail.com",
      age: 33,
      phone: "0102423423",
      access: "user",
    },
    {
      id: 19,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ali",
      lastname: "sayed",
      fullname: "ali sayed",
      email: "ali@gmail.com",
      age: 18,
      phone: "01143219323",
      access: "admin",
    },
    {
      id: 20,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "khaled",
      lastname: "ahmed",
      fullname: "khaled ahmed",
      email: "khaled@gmail.com",
      age: 20,
      phone: "01184319323",
      access: "user",
    },
    {
      id: 21,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ahmed",
      lastname: "ali",
      fullname: "ahmed ali",
      email: "ahmed@gmail.com",
      age: 32,
      phone: "01243219323",
      access: "admin",
    },
    {
      id: 22,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ali",
      lastname: "sayed",
      fullname: "ali sayed",
      email: "ali@gmail.com",
      age: 25,
      phone: "0102219323",
      access: "admin",
    },
    {
      id: 23,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "mohamed",
      lastname: "ali",
      fullname: "mohamed ali",
      email: "mohamed@gmail.com",
      age: 18,
      phone: "01053219323",
      access: "admin",
    },
    {
      id: 24,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "sara",
      lastname: "sayed",
      fullname: "sara sayed",
      email: "sara@gmail.com",
      age: 26,
      phone: "013214723",
      access: "user",
    },
  ],
  [
    {
      id: 25,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "sara",
      lastname: "sayed",
      fullname: "sara sayed",
      email: "sara@gmail.com",
      age: 26,
      phone: "013214723",
      access: "user",
    },
    {
      id: 26,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ali",
      lastname: "sayed",
      fullname: "ali sayed",
      email: "ali@gmail.com",
      age: 18,
      phone: "01143219323",
      access: "admin",
    },
    {
      id: 27,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "khaled",
      lastname: "ahmed",
      fullname: "khaled ahmed",
      email: "khaled@gmail.com",
      age: 20,
      phone: "01184319323",
      access: "user",
    },
    {
      id: 28,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ahmed",
      lastname: "ali",
      fullname: "ahmed ali",
      email: "ahmed@gmail.com",
      age: 32,
      phone: "01243219323",
      access: "admin",
    },
    {
      id: 29,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "sara",
      lastname: "alaa",
      fullname: "sara ala",
      email: "sara@gmail.com",
      age: 22,
      phone: "0123124454",
      access: "admin",
    },
    {
      id: 30,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "hager",
      lastname: "ali",
      fullname: "hager ali",
      email: "hager@gmail.com",
      age: 33,
      phone: "0102423423",
      access: "user",
    },
    {
      id: 31,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ali",
      lastname: "sayed",
      fullname: "ali sayed",
      email: "ali@gmail.com",
      age: 25,
      phone: "0102219323",
      access: "admin",
    },
    {
      id: 32,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "mohamed",
      lastname: "ali",
      fullname: "mohamed ali",
      email: "mohamed@gmail.com",
      age: 18,
      phone: "01053219323",
      access: "admin",
    },
  ],
  [
    {
      id: 33,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "sara",
      lastname: "alaa",
      fullname: "sara ala",
      email: "sara@gmail.com",
      age: 22,
      phone: "0123124454",
      access: "admin",
    },
    {
      id: 34,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "hager",
      lastname: "ali",
      fullname: "hager ali",
      email: "hager@gmail.com",
      age: 33,
      phone: "0102423423",
      access: "user",
    },
    {
      id: 35,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "sara",
      lastname: "sayed",
      fullname: "sara sayed",
      email: "sara@gmail.com",
      age: 26,
      phone: "013214723",
      access: "user",
    },
    {
      id: 36,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ali",
      lastname: "sayed",
      fullname: "ali sayed",
      email: "ali@gmail.com",
      age: 18,
      phone: "01143219323",
      access: "admin",
    },
    {
      id: 37,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "khaled",
      lastname: "ahmed",
      fullname: "khaled ahmed",
      email: "khaled@gmail.com",
      age: 20,
      phone: "01184319323",
      access: "user",
    },
    {
      id: 38,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ali",
      lastname: "sayed",
      fullname: "ali sayed",
      email: "ali@gmail.com",
      age: 25,
      phone: "0102219323",
      access: "admin",
    },
    {
      id: 39,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "mohamed",
      lastname: "ali",
      fullname: "mohamed ali",
      email: "mohamed@gmail.com",
      age: 18,
      phone: "01053219323",
      access: "admin",
    },
    {
      id: 40,
      zipcode: Math.floor(Math.random() * 3000),
      address: "cario",
      fristname: "ahmed",
      lastname: "ali",
      fullname: "ahmed ali",
      email: "ahmed@gmail.com",
      age: 32,
      phone: "01243219323",
      access: "admin",
    },
  ],
];
const dataUsersSlice = createSlice({
  name: "dataUsersSlice",
  initialState: {
    dataTableUsers: JSON.parse(localStorage.DataTable || JSON.stringify(data)),
  },
  reducers: {
    addUserRedux: (state, action) => {
      if (state.dataTableUsers[state.dataTableUsers.length - 1].length < 8) {
        state.dataTableUsers[state.dataTableUsers.length - 1].push(
          action.payload
        );
      } else {
        state.dataTableUsers.push([action.payload]);
      }
      localStorage.setItem("DataTable", JSON.stringify(state.dataTableUsers));
    },
    removeUser: (state, action) => {
      state.dataTableUsers = state.dataTableUsers
        .map((arr) => arr.filter((item) => +item.id !== action.payload))
        .filter((arr) => arr.length);
      localStorage.setItem("DataTable", JSON.stringify(state.dataTableUsers));
    },
  },
});
export const { addUserRedux, removeUser } = dataUsersSlice.actions;
export default dataUsersSlice.reducer;
