export { default as Header } from "./1-header/Header";
export { default as Nav } from "./2-nav/Nav";
export { default as TopDeals } from "./3-topDeals/TopDeals";
export { default as ChartBox } from "./4-chartBox/ChartBox";
export { default as PieChartBox } from "./5-pieChartBox/PieChartBox";
export { default as AreaChartBox } from "./6-areaChartBox/AreaChartBox";
export { default as BarChartBox } from "./7-barChartBox/BarChartBox";
export { default as CaptionPage } from "./8-captionPage/CaptionPage";
export { default as ContainerChart } from "./9-containerChart/ContainerChart";
